services:
  db:
    image: postgres:latest
    container_name: ezwayAdminData
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: db_open_api
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro
    ports:
      - "5433:5432"

volumes:
  db_data:
