version: "3.9"
services:
  ezwayadminapi:
    container_name: ezwayadminapi
    image: metsakuur/shinhanekyc:admin
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    env_file:
      - .env
    environment:
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - webekycadmin
    volumes:
      - ./logs:/app/logs
networks:
  webekycadmin:
    driver: bridge

