spring.application.name=EzwayAdmin

spring.datasource.ezwayadmin.url=${SPRING_DATASOURCE_EZWAYADMIN_URL}
spring.datasource.ezwayadmin.username=${SPRING_DATASOURCE_EZWAYADMIN_USERNAME}
spring.datasource.ezwayadmin.password=${SPRING_DATASOURCE_EZWAYADMIN_PASSWORD}
spring.datasource.ezwayadmin.driver-class-name=${SPRING_DATASOURCE_EZWAYADMIN_DRIVER_CLASS_NAME}
spring.datasource.ezwayadmin.hikari.minimum-idle=${SPRING_DATASOURCE_EZWAYADMIN_HIKARI_MINIMUM_IDLE}
spring.datasource.ezwayadmin.hikari.maximum-pool-size=${SPRING_DATASOURCE_EZWAYADMIN_HIKARI_MAXIMUM_POOL_SIZE}
spring.datasource.ezwayadmin.hikari.connection-timeout=${SPRING_DATASOURCE_EZWAYADMIN_HIKARI_CONNECTION_TIMEOUT}

# security
application.security.jwt.secret-key=${APPLICATION_SECURITY_JWT_SECRET_KEY}
application.security.jwt.expiration=${APPLICATION_SECURITY_JWT_EXPIRATION}
application.security.jwt.refresh-token.expiration=${APPLICATION_SECURITY_JWT_REFRESH_TOKEN_EXPIRATION}
application.security.jwt.cookie-auth.name=${APPLICATION_SECURITY_JWT_COOKIE_AUTH_NAME}

# Log mybatis (c?u hình code)
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
logging.level.org.mybatis=DEBUG
logging.level.com.infoplus.ezway.EzwayAdmin.mapper=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG

# Minio
minio.url=${MINIO_URL}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.selfie-bucket=${MINIO_SELFIE_BUCKET}
minio.ocr-bucket=${MINIO_OCR_BUCKET}
minio.verify-bucket=${MINIO_VERIFY_BUCKET}
minio.c06-bucket=${MINIO_C06_BUCKET}
minio.pp-nfc-bucket=${MINIO_PP_NFC_BUCKET}
