spring.application.name=EzwayAdmin
server.port=8080
spring.datasource.ezwayadmin.url=jdbc:postgresql://103.174.212.221:5432/postgres
spring.datasource.ezwayadmin.username=postgres
spring.datasource.ezwayadmin.password=Shin@#2025

#spring.datasource.ezwayadmin.url=jdbc:postgresql://localhost:5432/open_api_db
#spring.datasource.ezwayadmin.username=postgres
#spring.datasource.ezwayadmin.password=123456
spring.datasource.ezwayadmin.hikari.minimum-idle=10
spring.datasource.ezwayadmin.hikari.maximum-pool-size=50
spring.datasource.ezwayadmin.hikari.connection-timeout=30000

# security
application.security.jwt.secret-key=A282F99ED177A6638B6A9610FF081F379898402E77F93FA37AC291BDB1B00633
# a day
application.security.jwt.expiration=86400
#7 days
application.security.jwt.refresh-token.expiration=604800

# cookie
application.security.jwt.cookie-auth.name=auth

# Log mybatis
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
logging.level.org.mybatis=DEBUG
logging.level.com.infoplus.ezway.EzwayAdmin.mapper=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG

#Minio
minio.url=http://124.197.27.20:9000
minio.access-key=admin
minio.secret-key=Infoplus@!127&D2025
minio.selfie-bucket=ekyc-infogw-selfie
minio.ocr-bucket=ekyc-infogw-ocr
minio.verify-bucket=ekyc-infogw-verify
minio.c06-bucket=livenessdetection
minio.pp-nfc-bucket=ekyc-infogw-pp-nfc